version: '2.4'

services:
    server:
        build:
            context: .
            dockerfile: src/linkservice/Dockerfile
        container_name: ${APP_NAME}_server
        ports:
            - "3000:3000"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PORT: ${POSTGRES_PORT}
        depends_on:
            - postgres
            - flyway
        volumes:
            - ./src/linkservice:/app

    client:
        build:
            context: .
            dockerfile: src/frontend/Dockerfile
        container_name: ${APP_NAME}_client
        ports:
            - "3001:3001"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PORT: ${POSTGRES_PORT}
            LINKSERVICE_BASE_URL: ${LINKSERVICE_BASE_URL}
        volumes:
            - ./src/frontend:/app

    postgres:
        image: postgres:12.6
        container_name: ${APP_NAME}_postges
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - postgres:/data/postgres

    flyway:
        image: flyway/flyway
        container_name: ${APP_NAME}_flyway
        command: -url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
        volumes:
            - ./db/migration:/flyway/sql
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4:5
        container_name: ${APP_NAME}_pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/root/.pgadmin
        depends_on:
            - postgres

volumes:
    postgres:
    pgadmin:
