version: '2.4'

services:
    frontend:
        build:
            context: ./src/frontend/
            dockerfile: ../../ops/dockerfile/frontend/dev.Dockerfile
            target: develop
        container_name: ${APP_NAME}_frontend
        ports:
            - "${FRONTEND_HTTP_PORT}:${FRONTEND_HTTP_PORT}"
        environment:
            API_URL: ${FRONTEND_API_URL}
            SERVER_PORT: ${FRONTEND_HTTP_PORT}
            LINK_SERVICE_ADDR: ${LINKSERVICE_GRPC_SERVICE_ADDR}
        volumes:
            - ./src/frontend:/app

    linkservice_rest:
        build:
            context: ./src/linkservice/
            dockerfile: ../../ops/dockerfile/linkservice/rest/dev.Dockerfile
            target: develop
        container_name: ${APP_NAME}_linkservice_rest
        ports:
            - "${LINKSERVICE_REST_SERVER_PORT}:${LINKSERVICE_REST_SERVER_PORT}"
        environment:
            DATABASE_URL: ${LINKSERVICE_DATABASE_URL}
            REST_SERVER_PORT: ${LINKSERVICE_REST_SERVER_PORT}
        depends_on:
            - postgres
            - migration
        volumes:
            - ./src/linkservice:/app

    linkservice_grpc:
        build:
            context: ./src/linkservice/
            dockerfile: ../../ops/dockerfile/linkservice/grpc/dev.Dockerfile
            target: develop
        container_name: ${APP_NAME}_linkservice_grpc
        environment:
            DATABASE_URL: ${LINKSERVICE_DATABASE_URL}
            GRPC_SERVER_PORT: ${LINKSERVICE_GRPC_SERVER_PORT}
        depends_on:
            - postgres
            - migration
        volumes:
            - ./src/linkservice:/app

    postgres:
        image: postgres:12.6
        container_name: ${APP_NAME}_postges
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - postgres:/data/postgres

    migration:
        build:
            context: .
            dockerfile: ./ops/dockerfile/migration/Dockerfile
        container_name: ${APP_NAME}_migration
        environment:
            DATABASE_URL: ${LINKSERVICE_DATABASE_URL}
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4:5
        container_name: ${APP_NAME}_pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/root/.pgadmin
        depends_on:
            - postgres

volumes:
    postgres:
    pgadmin:
