// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/google/wire"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/server"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/pkg/api"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/pkg/rpc"
	"go.uber.org/zap"
	"os"
)

// Injectors from wire.go:

func InitializeFrontendService() (*FrontendService, func(), error) {
	sugaredLogger, cleanup, err := InitLogger()
	if err != nil {
		return nil, nil, err
	}
	context, cleanup2, err := InitContext()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	frontendServer, err := NewGRPCClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	frontend, cleanup3, err := InitServer(context, sugaredLogger, frontendServer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	frontendService, err := InitFrontendService(sugaredLogger, frontend)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return frontendService, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type FrontendService struct {
	Log *zap.SugaredLogger
	Srv *server.Frontend
}

var FrontendSet = wire.NewSet(
	InitFrontendService,
	InitContext,
	InitLogger,
	InitClient,
	NewGRPCClient,
	InitServer,
)

func InitFrontendService(log *zap.SugaredLogger, f *server.Frontend) (*FrontendService, error) {
	return &FrontendService{
		Log: log,
		Srv: f,
	}, nil
}

func InitContext() (context.Context, func(), error) {
	ctx := context.Background()

	cb := func() {
		ctx.Done()
	}

	return ctx, cb, nil
}

func InitLogger() (*zap.SugaredLogger, func(), error) {
	logger, _ := zap.NewProduction()

	cleanup := func() {
		logger.Sync()
	}

	sugar := logger.Sugar()

	return sugar, cleanup, nil
}

func InitClient() (*api.Client, error) {
	client, err := api.NewClient(os.Getenv("LINKSERVICE_BASE_URL"), nil)
	if err != nil {
		return nil, err
	}

	return client, nil
}

func NewGRPCClient(ctx context.Context) (*rpc.FrontendServer, error) {
	client, err := rpc.NewGRPCClient(ctx)
	if err != nil {
		return nil, err
	}

	return client, nil
}

func InitServer(ctx context.Context, log *zap.SugaredLogger, fe *rpc.FrontendServer) (*server.Frontend, func(), error) {
	server2 := server.NewFrontendServer(ctx, log, fe)

	cleanup := func() {
		server2.
			Stop()
	}
	server2.
		Start()

	return server2, cleanup, nil
}
