// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/caarlos0/env/v6"
	"github.com/google/wire"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/files"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/config"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/linksrv"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/server"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/server/handler"
	"go.uber.org/zap"
	"strconv"
)

// Injectors from wire.go:

func InitializeFrontend() (*Frontend, func(), error) {
	logger, cleanup, err := InitLogger()
	if err != nil {
		return nil, nil, err
	}
	config, err := InitConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	templates, err := InitTemplates()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	frontend, cleanup2, err := InitServer(config, templates, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	diFrontend, err := InitFrontend(logger, frontend)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return diFrontend, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Frontend struct {
	Log *zap.Logger
	Srv *server.Frontend
}

var FrontendSet = wire.NewSet(
	InitFrontend,
	InitConfig,
	InitLogger,
	InitTemplates,
	InitServer,
)

func InitFrontend(log *zap.Logger, f *server.Frontend) (*Frontend, error) {
	return &Frontend{
		Log: log,
		Srv: f,
	}, nil
}

func InitConfig() (*config.Config, error) {
	cfg := &config.Config{}
	if err := env.Parse(cfg); err != nil {
		return nil, err
	}

	return cfg, nil
}

func InitLogger() (*zap.Logger, func(), error) {
	logger, _ := zap.NewProduction()

	cleanup := func() {
		_ = logger.Sync()
	}

	return logger, cleanup, nil
}

func InitTemplates() (*files.Templates, error) {
	return files.InitTemplates()
}

func InitServer(conf *config.Config, tmp *files.Templates, log *zap.Logger) (*server.Frontend, func(), error) {
	linkService, err := linksrv.InitLinkServiceClient(conf.LinkServiceAddr)
	if err != nil {
		return nil, nil, err
	}

	h := handler.InitHandler(linkService, conf, tmp, log)
	srv := server.NewFrontendServer(strconv.Itoa(conf.ServerPort), h, log)

	cleanup := func() {
		_ = srv.Stop()
	}

	srv.Start()

	return srv, cleanup, nil
}
