// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"context"
	"github.com/google/wire"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/internal/server"
	"github.com/lapitskyss/go_backend_1_project/src/frontend/pkg/api"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeFrontendService() (*FrontendService, func(), error) {
	sugaredLogger, cleanup, err := InitLogger()
	if err != nil {
		return nil, nil, err
	}
	context, cleanup2, err := InitContext()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, err := InitClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	frontend, cleanup3, err := InitServer(context, sugaredLogger, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	frontendService, err := InitFrontendService(sugaredLogger, frontend)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return frontendService, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type FrontendService struct {
	Log *zap.SugaredLogger
}

var FrontendSet = wire.NewSet(
	InitFrontendService,
	InitContext,
	InitLogger,
	InitClient,
	InitServer,
)

func InitFrontendService(log *zap.SugaredLogger, f *server.Frontend) (*FrontendService, error) {
	return &FrontendService{
		Log: log,
	}, nil
}

func InitContext() (context.Context, func(), error) {
	ctx := context.Background()

	cb := func() {
		ctx.Done()
	}

	return ctx, cb, nil
}

func InitLogger() (*zap.SugaredLogger, func(), error) {
	logger, _ := zap.NewProduction()

	cleanup := func() {
		logger.Sync()
	}

	sugar := logger.Sugar()

	return sugar, cleanup, nil
}

func InitClient() (*api.Client, error) {
	client := api.NewClient(nil)
	return client, nil
}

func InitServer(ctx context.Context, log *zap.SugaredLogger, client *api.Client) (*server.Frontend, func(), error) {
	server2 := server.NewFrontendServer(ctx, log, client)

	cleanup := func() {
		server2.
			Stop()
	}
	server2.
		Start()

	return server2, cleanup, nil
}
