BEGIN;

CREATE TABLE IF NOT EXISTS links
(
    id          BIGINT generated BY DEFAULT AS IDENTITY,
    url         varchar(2048) NOT NULL,
    hash        varchar(20) NOT NULL,
    created_at  TIMESTAMP DEFAULT current_timestamp,

    CONSTRAINT links_id_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS links_hashx ON links (hash);

CREATE TABLE IF NOT EXISTS redirects
(
    id          BIGINT generated BY DEFAULT AS IDENTITY,
    link_id     BIGINT NOT NULL,
    created_at  TIMESTAMP DEFAULT current_timestamp,

    CONSTRAINT redirects_id_pkey PRIMARY KEY (id),
    CONSTRAINT redirects_fk_link_id FOREIGN KEY (link_id) REFERENCES links (id) ON DELETE RESTRICT
);

COMMIT;
