// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lapitskyss/go_backend_1_project/src/linkservice/internal/services/redirectsrv (interfaces: RedirectStore)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	redirectsrv "github.com/lapitskyss/go_backend_1_project/src/linkservice/internal/services/redirectsrv"
)

// MockRedirectStore is a mock of RedirectStore interface.
type MockRedirectStore struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectStoreMockRecorder
}

// MockRedirectStoreMockRecorder is the mock recorder for MockRedirectStore.
type MockRedirectStoreMockRecorder struct {
	mock *MockRedirectStore
}

// NewMockRedirectStore creates a new mock instance.
func NewMockRedirectStore(ctrl *gomock.Controller) *MockRedirectStore {
	mock := &MockRedirectStore{ctrl: ctrl}
	mock.recorder = &MockRedirectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectStore) EXPECT() *MockRedirectStoreMockRecorder {
	return m.recorder
}

// GetRedirectLink mocks base method.
func (m *MockRedirectStore) GetRedirectLink(arg0 context.Context, arg1 string) (*redirectsrv.RedirectLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedirectLink", arg0, arg1)
	ret0, _ := ret[0].(*redirectsrv.RedirectLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedirectLink indicates an expected call of GetRedirectLink.
func (mr *MockRedirectStoreMockRecorder) GetRedirectLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedirectLink", reflect.TypeOf((*MockRedirectStore)(nil).GetRedirectLink), arg0, arg1)
}

// SaveRedirectStatistics mocks base method.
func (m *MockRedirectStore) SaveRedirectStatistics(arg0 context.Context, arg1 redirectsrv.Redirect) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRedirectStatistics", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRedirectStatistics indicates an expected call of SaveRedirectStatistics.
func (mr *MockRedirectStoreMockRecorder) SaveRedirectStatistics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRedirectStatistics", reflect.TypeOf((*MockRedirectStore)(nil).SaveRedirectStatistics), arg0, arg1)
}
