name: golangci-lint
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint-frontend
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: src/frontend
          args: --config=.golangci.yml
      - name: golangci-lint-linkservice
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: src/linkservice
          args: --config=.golangci.yml